ProxyPass /phoenix/rest/register/windowsAgent https://111.223.51.37/phoenix/rest/register/windowsAgent
ProxyPassReverse /phoenix/rest/register/windowsAgent https://111.223.51.37/phoenix/rest/register/windowsAgent
ProxyPass /phoenix/rest/windowsAgent/update https://111.223.51.37/phoenix/rest/windowsAgent/update
ProxyPassReverse /phoenix/rest/windowsAgent/update https://111.223.51.37/phoenix/rest/windowsAgent/update
SSLProxyEngine on
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerExpire off
 
#Required for upgrade Windows Agent on FortiSIEM 6.4.0+
 
ProxyPass /WinAgentUpgrade/FSMLogAgent.exe https://111.223.51.37/WinAgentUpgrade/FSMLogAgent.exe
ProxyPassReverse /WinAgentUpgrade/FSMLogAgent.exe https://111.223.51.37/WinAgentUpgrade/FSMLogAgent.exe
 
ProxyPass /WinAgentUpgrade/AutoUpdate.exe https://111.223.51.37/WinAgentUpgrade/AutoUpdate.exe
ProxyPassReverse /WinAgentUpgrade/AutoUpdate.exe https://111.223.51.37/WinAgentUpgrade/AutoUpdate.exe
 
#Required for Windows Agent 5.0.0 or later
 
ProxyPass /phoenix/rest/device/update https://111.223.51.37/phoenix/rest/device/update
ProxyPassReverse /phoenix/rest/device/update https://111.223.51.37/phoenix/rest/device/update
 
#Required for Windows Agent 7.1.0 or later
 
ProxyPass /phoenix/rest/osquery/result https://111.223.51.37/phoenix/rest/osquery/result
ProxyPassReverse /phoenix/rest/osquery/result https://111.223.51.37/phoenix/rest/osquery/result